#!/usr/bin/env python3
"""Generate workflow contract mirrors from contracts/workflow.json.

The JSON file is the only hand-edited workflow topology. Backend, engine and
frontend consume generated language-native constants so adding or renaming a
stage cannot silently drift between three hand-maintained tables.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts" / "workflow.json"
OUTPUTS = {
    "python": ROOT / "backend" / "app" / "generated" / "workflow_contract.py",
    "engine": ROOT / "engine" / "src" / "generated" / "workflow-contract.ts",
    "frontend": ROOT / "frontend" / "app" / "generated" / "workflowContract.ts",
}


def _load() -> dict[str, Any]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    stages = data.get("stages")
    if not isinstance(stages, list) or not stages:
        raise SystemExit("workflow contract must contain a non-empty stages array")

    ids = [stage.get("id") for stage in stages]
    if any(not isinstance(stage_id, str) or not stage_id for stage_id in ids):
        raise SystemExit("every workflow stage requires a non-empty string id")
    if len(ids) != len(set(ids)):
        raise SystemExit("workflow stage ids must be unique")

    id_set = set(ids)
    for stage in stages:
        nxt = stage.get("next")
        if nxt is not None and nxt not in id_set:
            raise SystemExit(f"stage {stage['id']} points to unknown next stage {nxt}")
        kind = stage.get("kind")
        if kind not in {"production", "approval", "critique", "terminal"}:
            raise SystemExit(f"stage {stage['id']} has invalid kind {kind}")
        if kind in {"approval", "critique"} and stage.get("produced_stage") not in id_set:
            raise SystemExit(f"stage {stage['id']} requires a valid produced_stage")
        if not isinstance(stage.get("agent"), str) or not stage["agent"]:
            raise SystemExit(f"stage {stage['id']} requires agent")
        if stage.get("ui_stage") not in {"plan", "plan_approval", "render", "render_approval", "compose", "review"}:
            raise SystemExit(f"stage {stage['id']} has invalid ui_stage")

    # Ensure the declared next pointers form the same linear order as the file.
    for index, stage in enumerate(stages):
        expected = stages[index + 1]["id"] if index + 1 < len(stages) else None
        if stage.get("next") != expected:
            raise SystemExit(
                f"stage order mismatch: {stage['id']} next={stage.get('next')!r}, expected {expected!r}"
            )
    return data


def _derived(data: dict[str, Any]) -> dict[str, Any]:
    stages = data["stages"]
    stage_order = [stage["id"] for stage in stages]
    production = [stage["id"] for stage in stages if stage["kind"] == "production"]
    next_stage = {stage["id"]: stage.get("next") for stage in stages}
    stage_agent = {stage["id"]: stage["agent"] for stage in stages}
    approval = {
        stage["id"]: stage["produced_stage"] for stage in stages if stage["kind"] == "approval"
    }
    critique = {
        stage["id"]: stage["produced_stage"] for stage in stages if stage["kind"] == "critique"
    }
    gate_agent = {stage["id"]: stage["agent"] for stage in stages if stage["kind"] == "approval"}
    stage_to_ui = {stage["id"]: stage["ui_stage"] for stage in stages}
    representative: dict[str, str] = {}
    for stage in stages:
        representative.setdefault(stage["agent"], stage["id"])
    return {
        "stage_order": stage_order,
        "production": production,
        "next_stage": next_stage,
        "stage_agent": stage_agent,
        "approval": approval,
        "critique": critique,
        "gate_agent": gate_agent,
        "stage_to_ui": stage_to_ui,
        "representative": representative,
    }


def _py_tuple(name: str, values: list[str]) -> str:
    body = "\n".join(f'    "{value}",' for value in values)
    return f"{name}: tuple[StageId, ...] = (\n{body}\n)\n"


def _py_map(name: str, values: dict[str, Any], value_type: str = "str") -> str:
    lines = []
    for key, value in values.items():
        rendered = "None" if value is None else json.dumps(value, ensure_ascii=False)
        lines.append(f'    "{key}": {rendered},')
    return f"{name}: dict[str, {value_type}] = {{\n" + "\n".join(lines) + "\n}\n"


def render_python(data: dict[str, Any], d: dict[str, Any]) -> str:
    literal = ",\n    ".join(json.dumps(v) for v in d["stage_order"])
    return (
        "# Generated by scripts/generate_workflow_contract.py. DO NOT EDIT.\n"
        "from __future__ import annotations\n\n"
        "from typing import Literal\n\n"
        f"WORKFLOW_VERSION = {int(data['workflow_version'])}\n\n"
        "StageId = Literal[\n    " + literal + "\n]\n\n"
        + _py_tuple("PHASE2_STAGE_ORDER", d["stage_order"]) + "\n"
        + _py_tuple("PRODUCTION_STAGE_SEQUENCE", d["production"]) + "\n"
        + _py_map("NEXT_STAGE", d["next_stage"], "str | None") + "\n"
        + _py_map("STAGE_AGENT_MAP", d["stage_agent"]) + "\n"
        + _py_map("GRAPH_STAGE_FOR_AGENT", d["representative"]) + "\n"
        + _py_map("APPROVAL_TO_PRODUCED_STAGE", d["approval"]) + "\n"
        + _py_map("CRITIQUE_TO_PRODUCED_STAGE", d["critique"]) + "\n"
        + _py_map("GATE_AGENT", d["gate_agent"]) + "\n"
        + _py_map("STAGE_TO_UI", d["stage_to_ui"])
    )


def _ts_array(name: str, values: list[str]) -> str:
    body = "\n".join(f'  "{value}",' for value in values)
    return f"export const {name} = [\n{body}\n] as const;\n"


def _ts_map(name: str, values: dict[str, Any], type_expr: str) -> str:
    lines = []
    for key, value in values.items():
        rendered = "null" if value is None else json.dumps(value, ensure_ascii=False)
        lines.append(f"  {key}: {rendered},")
    return f"export const {name}: {type_expr} = {{\n" + "\n".join(lines) + "\n};\n"


def render_engine(data: dict[str, Any], d: dict[str, Any]) -> str:
    return (
        "// Generated by scripts/generate_workflow_contract.py. DO NOT EDIT.\n"
        f"export const WORKFLOW_VERSION = {int(data['workflow_version'])} as const;\n\n"
        + _ts_array("STAGE_ORDER", d["stage_order"])
        + "export type StageId = (typeof STAGE_ORDER)[number];\n\n"
        + _ts_array("PRODUCTION_STAGE_SEQUENCE", d["production"])
        + "\n"
        + _ts_map("NEXT_STAGE", d["next_stage"], "Record<StageId, StageId | null>")
        + "\n"
        + _ts_map("STAGE_AGENT_MAP", d["stage_agent"], "Record<StageId, string>")
        + "\n"
        + _ts_map("GRAPH_STAGE_FOR_AGENT", d["representative"], "Record<string, StageId>")
        + "\n"
        + _ts_map("APPROVAL_TO_PRODUCED_STAGE", d["approval"], "Partial<Record<StageId, StageId>>")
        + "\n"
        + _ts_map("CRITIQUE_TO_PRODUCED_STAGE", d["critique"], "Partial<Record<StageId, StageId>>")
        + "\n"
        + _ts_map("GATE_AGENT", d["gate_agent"], "Partial<Record<StageId, string>>")
        + "\n"
        + _ts_map("STAGE_TO_UI", d["stage_to_ui"], "Record<StageId, UiWorkflowStage>")
        + '\nexport type UiWorkflowStage = "plan" | "plan_approval" | "render" | "render_approval" | "compose" | "review";\n'
    )


def render_frontend(data: dict[str, Any], d: dict[str, Any]) -> str:
    _ = data
    return (
        "// Generated by scripts/generate_workflow_contract.py. DO NOT EDIT.\n"
        + _ts_array("STAGE_ORDER", d["stage_order"])
        + "export type StageId = (typeof STAGE_ORDER)[number];\n"
        + 'export type UiWorkflowStage = "plan" | "plan_approval" | "render" | "render_approval" | "compose" | "review";\n\n'
        + _ts_map("STAGE_TO_UI", d["stage_to_ui"], "Record<StageId, UiWorkflowStage>")
    )


def main() -> int:
    check = "--check" in sys.argv[1:]
    data = _load()
    d = _derived(data)
    rendered = {
        "python": render_python(data, d),
        "engine": render_engine(data, d),
        "frontend": render_frontend(data, d),
    }

    dirty: list[Path] = []
    for key, path in OUTPUTS.items():
        expected = rendered[key]
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != expected:
                dirty.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    if dirty:
        print("workflow contract generated files are stale:")
        for path in dirty:
            print(f"  - {path}")
        print("run: python scripts/generate_workflow_contract.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
